### ISSUE TITLE
Smarter quotes

### ISSUE THREAD

**Issue by ig0774** [r-stein/sublime-text-latex-smart-quotes#2]
This is actually a really useful plugin, but (and this is basically an English-only concern), it doesn't seem to quite behave correctly when modifying already-existing text to add a possessive ('s):

![issue](https://cloud.githubusercontent.com/assets/212893/16949153/0cace03e-4db1-11e6-91bc-d6d7f0ac3110.gif)

It may be better to only turn `'` into smart quotes when either a) the selection is not empty or b) the character to left of the cursor is whitespace or the start of a line.

**Comment by r-stein** [comment]
Thanks. I should add punctuation marks to this [regex](https://github.com/r-stein/sublime-text-latex-smart-quotes/blob/1.0.8/Default.sublime-keymap#L54) and to [line 22](https://github.com/r-stein/sublime-text-latex-smart-quotes/blob/1.0.8/Default.sublime-keymap#L22) to add "close" quote, which does also fits a `'s`.
